---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gateway-config
  namespace: cyber-pi-intel
data:
  nginx.conf: |
    events {
        worker_connections 4096;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log warn;

        sendfile        on;
        keepalive_timeout  65;
        client_max_body_size 100M;

        # Upstream definitions
        upstream weaviate_http {
            server weaviate.cyber-pi-intel.svc.cluster.local:8080;
        }

        upstream neo4j_http {
            server neo4j.cyber-pi-intel.svc.cluster.local:7474;
        }

        upstream neo4j_bolt {
            server neo4j.cyber-pi-intel.svc.cluster.local:7687;
        }

        upstream backend_api {
            server backend-api.cyber-pi-intel.svc.cluster.local:8000;
        }

        # Main server block
        server {
            listen 80;
            server_name _;

            # Health check endpoint
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }

            # Weaviate routes
            location /weaviate/ {
                proxy_pass http://weaviate_http/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 300s;
                proxy_connect_timeout 75s;
            }

            # Backend API routes (including ML endpoints)
            location /api/ {
                proxy_pass http://backend_api/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 300s;
                proxy_connect_timeout 75s;
            }

            # Neo4j Browser (HTTP)
            location /neo4j/ {
                proxy_pass http://neo4j_http/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Root endpoint
            location / {
                return 200 '{
                    "service": "cyber-pi-intel Gateway",
                    "version": "1.0.0",
                    "status": "operational",
                    "endpoints": {
                        "api": "/api/",
                        "ml": "/api/ml/",
                        "weaviate": "/weaviate/v1/schema",
                        "neo4j": "/neo4j/",
                        "health": "/health"
                    }
                }';
                add_header Content-Type application/json;
            }
        }

    }

    # Stream block for TCP proxying (Neo4j Bolt, Redis)
    stream {
        upstream redis_backend {
            server redis.cyber-pi-intel.svc.cluster.local:6379;
        }

        upstream neo4j_bolt_backend {
            server neo4j.cyber-pi-intel.svc.cluster.local:7687;
        }

        server {
            listen 6379;
            proxy_pass redis_backend;
        }

        server {
            listen 7687;
            proxy_pass neo4j_bolt_backend;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
  namespace: cyber-pi-intel
  labels:
    app: nginx-gateway
    component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
        component: gateway
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-gateway-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
  namespace: cyber-pi-intel
  labels:
    app: nginx-gateway
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30888
    name: http
  selector:
    app: nginx-gateway
