apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-loader-script
  namespace: cyber-pi-intel
data:
  load_redis.py: |
    #!/usr/bin/env python3
    """Push threats to Redis highway"""
    import asyncio
    import json
    from datetime import datetime, timezone
    import hashlib
    import redis.asyncio as redis

    async def main():
        print("="*60)
        print("🚀 REDIS BULK LOAD")
        print("="*60)

        # Connect to Redis (internal service)
        redis_client = await redis.from_url(
            "redis://:cyber-pi-redis-2025@redis.cyber-pi-intel.svc.cluster.local:6379",
            encoding="utf-8",
            decode_responses=True
        )
        await redis_client.ping()
        print("✅ Connected to Redis")

        # Load data
        with open('/data/master_collection_20251031_014039.json') as f:
            data = json.load(f)

        items = data.get('items', [])
        print(f"📊 Found {len(items)} threats")

        queued = 0
        for i, item in enumerate(items):
            if i % 100 == 0 and i > 0:
                print(f"  Progress: {i}/{len(items)} ({i*100//len(items)}%)")

            threat_id = f"threat_{hashlib.sha256((item.get('title', '') + item.get('link', '')).encode()).hexdigest()[:16]}"

            # Extract source name from dict
            source_info = item.get('source', {})
            source_name = source_info.get('name', 'cyber-pi') if isinstance(source_info, dict) else str(source_info)

            # Ensure RFC3339 date format with timezone
            published = item.get('published', '')
            if published and not (published.endswith('Z') or '+' in published or '-' in published[-6:]):
                published += 'Z'  # Add UTC timezone if missing
            if not published:
                published = datetime.now(timezone.utc).isoformat()

            threat_data = {
                "threatId": threat_id,
                "title": item.get('title', 'Unknown')[:500],
                "content": item.get('content', '')[:10000],
                "source": source_name,
                "sourceUrl": item.get('link', ''),
                "industry": [item.get('category', 'General')],
                "severity": "medium",
                "threatType": [],
                "threatActors": [],
                "cves": [],
                "publishedDate": published,
                "ingestedDate": datetime.now(timezone.utc).isoformat()
            }

            # Store parsed threat
            await redis_client.setex(
                f"threat:parsed:{threat_id}",
                86400,
                json.dumps(threat_data)
            )

            # Queue for workers
            await redis_client.lpush("queue:weaviate", threat_id)
            await redis_client.lpush("queue:neo4j", threat_id)
            queued += 1

        print(f"\n✅ Queued {queued} threats")

        weaviate_len = await redis_client.llen("queue:weaviate")
        neo4j_len = await redis_client.llen("queue:neo4j")
        print(f"📊 queue:weaviate = {weaviate_len}")
        print(f"📊 queue:neo4j = {neo4j_len}")

        await redis_client.close()

    if __name__ == "__main__":
        asyncio.run(main())

---
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-bulk-load
  namespace: cyber-pi-intel
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: loader
        image: python:3.11-slim
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Installing dependencies..."
            pip install --quiet redis
            python3 /scripts/load_redis.py
        volumeMounts:
        - name: script
          mountPath: /scripts
        - name: data
          mountPath: /data
          readOnly: true
      volumes:
      - name: script
        configMap:
          name: redis-loader-script
      - name: data
        hostPath:
          path: /home/david/projects/cyber-pi/data/raw
          type: Directory
